version: '3.8'

services:
  database:
    image: postgres:alpine3.18
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: database
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_DB: ${DB_NAME}
  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    volumes:
      - chache:/data
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: api
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      SALT: ${SALT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: database
      POSTGRES_PORT: ${DB_HOST_PORT}
      POSTGRES_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_CONTAINER_PORT}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  db-data:
  chache: