services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: api
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    environment:
      PORT: ${PORT}
      HOST: ${HOST}